# Generated by Django 4.2.7 on 2023-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='book',
            field=models.ManyToManyField(related_name='writers', to='books.book'),
        ),
    ]
